spring.application.name=moment-backend

# PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/moment_local
spring.datasource.username=moment
spring.datasource.password=moment1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Redis Local
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false


# Server
server.port=8080

# Local JWT
jwt.secret-key=local-dev-jwt-secret-key-change-me-change-me-change-me