# Prod PostgreSQL / RDS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Prod Redis / ElastiCache
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}

# Prod Flyway
spring.flyway.enabled=true

# Prod ??
spring.jpa.show-sql=false
logging.level.root=warn

# prod ???? Swagger ????
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false