apiVersion: v1
kind: ConfigMap
metadata:
  name: moment-config
  namespace: default
data:
  DB_URL: jdbc:postgresql://moment-postgres:5432/moment
  REDIS_HOST: moment-redis
  REDIS_PORT: "6379"
  SERVER_PORT: "8080"