apiVersion: v1
kind: Secret
metadata:
  name: moment-secret
  namespace: default
type: Opaque
stringData:
  DB_USERNAME: moment
  DB_PASSWORD: moment1234
  JWT_SECRET: bW9tZW50c2VjcmV0a2V5Zm9ybG9jYWxkZXZlbG9wbWVudDEyMzQ1Njc4OTA=
  KAKAO_CLIENT_ID: f4c7c025c81b57486c08a43afd423e5d